### ISSUE TITLE
Defend against a key shenanigans attack by the server

### ISSUE THREAD

**Issue by exarkun** [PrivateStorageio/ZKAPAuthorizer#110]
The privacy features of challenge-bypass-ristretto are not guaranteed if the client cannot hide in a crowd of other users.  The size of the crowd is defined by the number of clients which redeem vouchers from a server using a particular signing key.  If a server offers a different signing key to each user, no user has a crowd and there are no privacy features.

Outside of the cryptographic protocol, the client must take steps to be sure it is not being attacked this way.  These steps must somehow convince the client that the server is signing a large number of tokens with the same key.

- [ ] [Identify suspicious ZKAPs](https://github.com/PrivateStorageio/ZKAPAuthorizer/issues/112)
- [ ] [Don't spend suspicious ZKAPs](https://github.com/PrivateStorageio/ZKAPAuthorizer/issues/113)
- [ ] [Expose suspicious ZKAPs in the HTTP API](https://github.com/PrivateStorageio/ZKAPAuthorizer/issues/114)

**Comment by exarkun** [comment]
If we introduced communication between otherwise unrelated clients then they could gossip about keys they've seen.  This could provide a very strong mechanism to defend against this kind of attack by the server.  A completely unrestricted gossip network is probably not feasible since it opens up clients to the reverse attack - lies by its peers about keys they've seen, casting unearned doubt on a server.  Because of the complexities implied there, I don't think this is the right path to pursue initially.

A weaker defense is for clients to keep track of the keys they have seen over the course of time.  This would allow a client to notice if a server is doing a bad job at being tricky with keys, at least.  A server could still try to identify clients and assign each of them a persistent, unique key.  However, if the client mixes up their payment details and network location between payments then they may have a chance of confusing such a server.  And once one client notices tricks are being played, the attention drawn may be enough to alert all clients.

A client keeping track of keys it has seen over time is probably a step towards clients comparing notes about what they've seen, anyway.  So maybe this makes sense for now.

Concretely, I suggest that the client record the signing key in its local database alongside vouchers/tokens and look upon changes to that key unfavorably over time.  Conveniently, this doesn't require changes to anything but the client storage plugin provided by ZKAPAuthorizer.

We *could* deliver the key to the client in the static plugin configuration but this raises concerns about future key rotation (rewriting the static configuration is hard) and I don't think it delivers appreciably more security.  In either approach, the client must just take whatever initial value someone gives it - the only difference is whether the value is given at configuration time or payment time (the value cannot make any difference until *after* payment because you do not see keys until after payment, so those two times are effectively the same).

**Comment by exarkun** [comment]
As far as concrete *behavior*, if the key doesn't change then no behavior needs to change.  If the client *does* see a new key on a subsequent redemption attempt, should it do anything differently?

I think what makes sense is for key changes to be allowed as long as they are not more frequent than some specified interval.  All other things being equal, the longer the interval, the better it is for the client.  However, at any specific interval, the more ZKAPs are being purchased the better it is for the client, too.  This suggests that a service with few clients should only rotate on a long interval (say once a year).  Services with more clients can pick shorter intervals (probably with some linear function).  Of course, we have no in-band mechanism for clients to learn how many other clients are using a service.  I suppose initially we should probably just hard-code (maybe literally in code, maybe in the configuration file) an acceptable minimum interval (ie, I can kick this can down the right, I guess).

Getting back to the point - if key rotation is seen more often than the configured interval, I think the ZKAPs should be marked as suspicious and not used without user intervention.  That will require some UI somewhere, of course...

**Comment by exarkun** [comment]
The above doesn't really make sense.  The mistake is in thinking suspiciousness is attributable to a particular voucher or redemption (and thus can be translated onto a group of ZKAPs).

At most generous, a redemption attempt that sees a suspicious key change should cast suspicion on all ZKAPs associated with the *previous* key since that is the one which has been noticed to go out of service before its time.

More realistically, suspicious key change behavior from an issuer should probably cast suspicion on the issuer itself.  If the *last* key went out of service early, that may be a good predictor that the *new* key will also go out of service early.  The trouble here is that by the time you *see* the key go out of service early, you may have spent most of the ZKAPs associated with it.  This is certainly the case if your only information about key changes comes from redemption attempts.

This brings up another point.  Observing the key during redemption attempts is not sufficient.  More frequent observations are required.  It's quite likely some clients will redeem vouchers so infrequently that they cannot determine if key rotations are suspicious or not without additional datapoints.

The easiest way to make more observations is probably to poll an endpoint on the issuer that just returns the public key.  This still isn't as good as the gossip idea above but at least it makes the single-client-perspective stronger.  If the client sees the key every few days and sees it isn't changing more often than every few quarters then they're not vulnerable when they only redeem every year or so because they have a history showing that perhaps only one or two key rotations have happened since their last redemption.  Without the extra observations the key could have rotated every 5 minutes for all they know.

So #112 certainly doesn't make sense.  #113 should be replaced with something more like "don't spend ZKAPs on a suspicious service" and #114 should be replaced with something more like "Expose issuer suspiciousness status HTTP API".

**Comment by meejah** [comment]
The "privacy pass" implementation [talks about this](https://github.com/privacypass/challenge-bypass-server#nizk-proofs-of-discrete-log-equality) I think in the context of clients having a consistent view of the tuple (G, Y) (which is the generator and commitment / public-key)

> "One way to ensure this consistent view is to pin one key at a time in each copy of the client and use software update mechanisms for rotation. A more flexible way is to pin a reference that allows each client to fetch the latest version of the key from a trusted location."

I guess the kool, moderne "trusted location" would be some message in a blockchain somewhere, right? ;)

**Comment by keks** [comment]
If the key never changes, `(G, Y)` could just be compiled into the clients. If it _does_ change, a certificate-transparency-like thing would probably be good, except we don't need that level of scalability (only a few certs/`(G, Y)` tuples)

**Comment by keks** [comment]
And yeah, gossip could be a less-scalable CT thing I guess. If you gossip, you could hard-code a public key that is allowed to rotate the (G, Y) tuple and only allow gossiping messages that are signed by that key. The gossipped messages would include a time stamp, a new (G, Y) tuple as well as the hash of the previous message. If you observe a fork, a message from the far future, or too frequent re-keying, complain somewhere publicly (insert wild hand-waving gesture here).

**Comment by exarkun** [comment]
Considering all of the above, for now, I plan to expand the configuration for ZKAPAuthorizer clients to include a small set of allowed public keys.  A client can be distributed with a configuration that includes a few keys (one for current use, a few more to support future key rotations without disrupting clients).

Distribution of new public keys will be done by distributing a new version of the client.  Fancier distribution systems are still possible in the future.  The basic logic of checking whether a given public key is acceptable or not should remain the same, as should the action taken with tokens signed with an untrusted public key.
